import React from 'react';
import './index.scss';

// base64位的loading图
const LOADGIF_BASE64 = `data:image/gif;base64,R0lGODlhDwAPANUAAP////f3//f39+/39+/v9+bv7+bm797m5t7m797e5tbe5s7e5s7W5s7W3sXW
    3sXO3r3O3r3O1r3F1rXFzrXF1rW9zq29zqW1zqW1xZy1xZytxZStvZSlvYylvYyltYSctXuUrXOUrXOMrWuMrWuMpWuEpWOEpWOEnGN7nFp7nFJzlEpzlEprlE
    JrjDFahClSeyFKexBCaxBCcwAxY/4BAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQFBwA0ACwAAAAADwAP
    AAAGm0CAEEBAySKAAUcxbEZmMxUA9HoxhQSCEAYFqKoGoSASaYyhiipoSCCTC6rZ56UaABDCgsJBlsxaLgoFICsaYgQFDREvLA0YKSuRBXxuDROEkSsmEm4PCA
    YRGCIhGA8FQgcRDAIFEQ8aCiAiIiAXAgC3Ag8RChoSBh2zIgdDig8CGhoGAhK0Q2OqAMkXTc+7YRLJp9XVBRkRAU1BACH5BAUHADQALAAAAAAPAA8AAAaUQIAQ
    IHBECMNkshCJKACWGQwxFBSEjSZANZtFhtmHQaCVSZPNpkIRYXQjA44EQDhkI1nRLJNxvVxJVg0TMSQtL4guAgoPaRMNKX4qKRsGjU0MDRkkJBICSQwRDgQKGg
    8iJSsrJBpPdAAGGhoEIh8dqqpJFxoZAB0iEhMpq0MFsnMbIiJjEldCArtUpyIWStYCH5VJQQAh+QQFBwA0ACwAAAAADwAPAAAGl0CAUHiIFIQEwXApiEQcgIKT
    MBQoAQynQDEdPiIM65fgeFadkUcBYdQCIkID4xsxRBpt2Ow0HCi+eBIqM4QyBhIaiRoYFC+EhCoRGYoSCiIgLC0fCkMRGhcFBiAhKw0uLy8qIANRAAIdIhgrFw
    oqqC8bQxYiIg8rKQUDIKicQrwgCCsrIHHFQiAiFwAmyghLSwdKEisa10EAIfkEBQcANAAsAAAAAA8ADwAABptAgFDIeAiGSGQhElEACJHGUTgwCB2RB+DALAwv
    mosBGgE0skiNWqNgRARMa+GokGTU56VCcHYgCQ8ZEw0NCkxMAoEdIiIkDROHDwoEH4wiHyUkKTEiDEgbjBIdKxIuJDMzMioZAAYSBhMrKwIvLRmoqEMCKSskAC
    ovGBEwMzBDErIaACkvLgMAEQhDBSQrThsvLx9J3AYuLhJIQQAh+QQFBwA0ACwAAAAADwAPAAAGmUCAEBCIZAzDZLKg0UgAhshDoBRemgBGJEIVgkQSAVMzeEQa
    w4No3TFINAopdX75ikAKjbkg0B6EBQ8ZISIYEQYIZlsSJiuOKyAUDVtbDgWPKRcNLC9nBQRdGpAFCi4tMxKVCgVCCAADKi8fMyoFlBEEQyAvLwozM1yTXEIGvC
    oAvzBCBLlCCrwgACq/EVUAChsDABEyJ9pDQQAh+QQFBwA0ACwAAAAADwAPAAAGl0CAEGDYfATDZNIiEj0ACM1lMCxIBIbmBiDRaApD0iplkYg6gIw0uWqvOh8R
    wQsmCBUa8ark1CgIDhEMSQISJCQZDQwRjA8GHCkqLy4pDROMEQ8KAi4vni0kMRMNBUhDnS4YGTMiEQ2MDQd2EhsDETMziwoKmBFJMDMyAIxYD65DtzMqw8cApU
    MIwBYAvBFgSkoEEQ6mQkEAIfkEBQcANAAsAAAAAA8ADwAABpZAgFCoWUkAgsNwCUCsVibARQRaKgxC0BMBEomGitcLNCikVg+vZbgRv1SKywoj6ggA2AFIJXY1
    ViEgBgYXGhFgHy0sXQoSGo8ZESozlDMvFBiPjxIFMpUqEhENEQ8Kd0InMzARBaIRBhGkDFgAhwKxrQgFD7ERpwAOEQ4EpAICDKRDxBGmsQxCxsq4wLG/SwIEQq1
    KS0EAIfkEBQcANAAsAAAAAA8ADwAABphAmpAmcbkMgKQSMKR9Xq8NTbEiFYaICG3geqUAmtVKIgTAZrAI5kUDkFYpQXlGn2VaL4F4YpAgMzQydCQuEisdEiIiG0
    sMIjEpJCUfiiIfBQsPEZsTDSSKHTQPApubCg0OE4AES5oOAgo0Vw0aGhkSsQJXBkJyDAq1tUxNbZsEBRcaF0NXZQ80DkLNvdEEU9JNS0oCDwzEQQA7
`;

class Loading extends React.Component {
    render () {
        return (
            <div className="c-loading">
                <img src={LOADGIF_BASE64} alt=""/>
                <span>{this.props.isShowText ? this.props.text : ''}</span>
            </div>
        );
    }
}

// 默认属性
Loading.defaultProps = {
    text: '加载中···',
    isShowText: false
};

export default Loading;